spring:
  application:
    name: app-gateway
  cloud:
    discovery:
      enabled: false

server:
  port: 8085

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
      camunda-engine:
        url: http://localhost/engine-rest
      order-service:
        url: http://localhost:8086
