spring:
  application:
    name: card-service
  cloud:
    discovery:
      enabled: false
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/process-engine
    username: camunda
    password: camunda

server:
  port: 8087

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
      camunda-engine:
        url: ${camunda.engine.url}
      order-service:
        url: http://localhost:8086

camunda:
  engine:
    url:  http://localhost/engine-rest