spring:
  application:
    name: card-service
  cloud:
    discovery:
      enabled: false

server:
  port: 8087

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
      camunda-engine:
        url: ${camunda.engine.url}
      order-service:
        url: http://localhost:8086

camunda:
  engine:
    url:  http://localhost/engine-rest